### ISSUE TITLE
reduce API usage when searching for artifact to download

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/asset-artifact-download-action#1]
This action is using a lot of API calls when searching for an artifact to download (when `target` is a branch or commit). It's even worse if it fails to find an artifact due to the artifact not existing (possibly because the workflow to build the artifact is till running, making the artifact not available). The high API usage can result in hitting API limits, failing workflows due to `API rate limit exceeded for installation ID 21904452.` etc

**Comment by bhazzard** [comment]
Super low priority
